import Header from "@/components/layout/Header";
import "./globals.css";
import { CartProvider } from "@/context/CardContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>

          <Header />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
